### ISSUE TITLE
UX-justeringar resultatformulär

### ISSUE THREAD

**Issue by lostminds** [josve/mahjong#5]
Vet inte om komponenterna stödjer det, men det vore också fint om menyerna tydligare skiljde i stil på när inget är valt ("Välj vinnare") och när något alternativ är valt. Nu ser de lite lika ut. 

För fälten med poäng tänker jag att det vore bra om vi kunde få bort pilknapparna, eller göra så att de steppar två poäng i taget efter som de nu stegar ett poäng i taget som inte är giltigt. 

![Screenshot 2024-10-15 at 09 31 35](https://github.com/user-attachments/assets/15c4abc3-8e61-4deb-b4d4-57615ae2bc6b)

**Comment by josve** [comment]
https://mui.com/material-ui/all-components/

**Comment by josve** [comment]
fixat förutom att ta bort knappen och ändra till 2. men validerar att det är jämnt
