### ISSUE TITLE
Lägg in poängräknare från gamla systemet

### ISSUE THREAD

**Issue by lostminds** [josve/mahjong#60]
I gamla systemet finns en poängräknare som kan vara bra i komplicerade fall:
https://www.lostminds.com/mahjong/score_calculator.php

Den borde vi kopiera över så att något liknande finns även i nya systemet.

**Comment by lostminds** [comment]
@josve verkar som att du jobbar på något liknande detta #64 ? Eller var det något annat?

**Comment by josve** [comment]
ja precis håller på och lägger in den

**Comment by josve** [comment]
har lagt in nu en variant som skall räkna ut alla värden rätt nu liknande din räknare @lostminds nu med hjälp av react. däremot så är den inte så snygg

**Comment by josve** [comment]
jag är klar

**Comment by josve** [comment]
Har stylat till den lite nu så att den liknar den gamla

**Comment by josve** [comment]
Men du får gärna tweaka mer
