### ISSUE TITLE
Lägg in inställning för hur poäng och mahjonger ska visas

### ISSUE THREAD

**Issue by lostminds** [josve/mahjong#66]
Det verkar ju råda lite delade meningar om hur grafen ska visa mahjong-markeringen, eller poängen beroende på hur en ser på det. Jag tycket det nya sättet är konstigt men du och martin verkar ju gilla det. Så jag skulle vilja ha en inställning så en kan välja.

Tex en checkbox bara på sidan som gör att den laddas om med en extra parameter typ (alternative_mahjong_graph=true) som sedan används för genereringen av grafen eller datan.

Som jag skulle vilja ha det (dvs som det fungerade i tidigare systemet) när denna inställning är på:
- Varje punkt i grafen visar poängen vi denna rundas början (dvs 500 på första och poängen från senaste rundan på sista).
- För rundor som har registrerade resultat visas en cirkel som indikerar vem som fick mahjong denna runda, och i tooltippen visas efter poängen per spelare hur mycket vann denna omgång. 
- För rundor utan registrerat resultat visas endast poängen (dvs resultatet från tidigare omgång)

![Screenshot 2024-10-27 at 11 28 53](https://github.com/user-attachments/assets/604bcd3d-e4ee-4a6e-9c6c-cc80b2a4d8a8)
![Screenshot 2024-10-27 at 11 29 01](https://github.com/user-attachments/assets/735e65a3-43dc-4b2a-9bf8-4df2f4e9c753)

**Comment by josve** [comment]
Fixat nu

**Comment by josve** [comment]
Det är en setting på din användare

**Comment by lostminds** [comment]
Ojoj, Har en en användare nu? Jag såg en "logga in"-knapp i menyn tidigare och misstänkte att det var något i görningen, får prova det

**Comment by josve** [comment]
Kolla i readme.md hur du testar lokalt
