### ISSUE TITLE
Kompileringsfel: [auth][error] MissingSecret efter uppdatering till Next.js 15.0.1

### ISSUE THREAD

**Issue by lostminds** [josve/mahjong#70]
Uppdaterade main nu och körde igång för att jag tänkte jobba lite mer på styling och layout-grejer, men får ett komplieringsfle när jag försökker köra komma in på http://localhost:3000 för att testa det lokalt:

```
Module not found: Can't resolve 'next-auth'
> 1 | import NextAuth from "next-auth"
    | ^
  2 |  
  3 | export const { handlers, signIn, signOut, auth } = NextAuth({
  4 |   providers: [],

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/middleware.ts
 ○ Compiling /src/middleware ...
 ✓ Compiled /_error in 462ms (254 modules)
 GET / 404 in 5ms
 ○ Compiling /_not-found ...
 ✓ Compiled /_not-found in 5s (1604 modules)
 GET /_next/static/webpack/cc16436c265a03eb.webpack.hot-update.json 500 in 8ms
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET / 404 in 0ms

```

I browser visas även: Next.js (14.2.10) is outdated [(learn more)](https://nextjs.org/docs/messages/version-staleness)
Kanske något vi behöver uppdatera?

**Comment by lostminds** [comment]
Ok, verkade mer vara jag som kanske hade en för gamal version av npm installerat, så jag uppdaterade till senaste, Next.js 15.0.1 och nu fungerar det att bygga igen. Men jag får istället ett gäng varningar / errors om MissingSecret:
```
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/@auth/core/lib/utils/assert.js:66:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/@auth/core/index.js:91:95)
```
Kanske någon ny requirement från version 15?

**Comment by lostminds** [comment]
Verkar fungera lite skakigt överlag med NextJS 15 efter att jag uppdaterat, så det var kanske ett misstag att uppdatera. Får ganska mycket varningar och den verkar överbelasta "servern" lokalt som efter några omladdningar slutar funka och klagar på "too many connections" så jag får starta om Docker. Kanske stängs de inte korrekt?

**Comment by josve** [comment]
Nej, gör ingen uppdatering till 15. felen du får beror på att jag har lagt in stöd för authentisering även om det inte behövs

**Comment by josve** [comment]
Kör så här:

npm install 
följt av
npx auth secret

så funkar det nog. testa annars att spara .env.local filen, gör en ny incheckning och kör från den

**Comment by lostminds** [comment]
Ok, tack. Lyckades installera om nextJS 14.2.10 och den där auth-komponenten så nu får jag inge fel och det verkar funka fint.
