### ISSUE TITLE
Nya matcher syns inte i match-listan?

### ISSUE THREAD

**Issue by lostminds** [josve/mahjong#8]
Jag skapade en ny testmatch för att prova inmatningen, men om jag nu tittar på https://mastersystem.josve.se/ så syns den inte i listan

Det går dock fortfarande att gå in på match-sidan för den:
https://mastersystem.josve.se/match/665232ee-7637-48ae-835e-27a226a798e7

**Comment by josve** [comment]
Den var statiskt cachad utan att invalideras, ändrade så att den omskapas om det behövs varje minut:

https://github.com/josve/mahjong/commit/bf3f6ee986bc99450422f5baf7b102441c0dc280
