### ISSUE TITLE
Ändra sid-title så den inte är samma för alla sidor

### ISSUE THREAD

**Issue by lostminds** [josve/mahjong#9]
Nu heter alla sidor "Mahjong Master System 4.0", vilket gör det lite svårt att skilja på tabbar om en har flera öppna.

Förslagsvis ändrar vi dem till ex "Matcher - Mahjong Master System", "Statistik - Mahjong Master System", "<Match namn> - Mahjong Master System" etc.

**Comment by josve** [comment]
fixat, kanske finns någon kvar
